### ISSUE TITLE
Define API versioning

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/marketplace-rest-api#47]
We need to define and implement how we are going to deal with API versioning.

**Comment by autumnfound** [comment]
I think the best way to do this going forward would be to use a custom header as defined in the REST API guidelines site https://restfulapi.net/versioning/. This allows constant URIs, and removes the burden of hacking together an Accept string. 

## Proposed solution:
*New headers*
Accept-Version: Target API version
Deprecation: Header to warn the user that the endpoint has been deprecated since version _N_. This allows a more natural period of degredation. While not yet official, this header is WIP from ietf https://tools.ietf.org/html/draft-dalal-deprecation-header-00

Using custom code, we can keep old functionality in some working state going forward, detecting on Accept-Version and passing a Deprecation header to inform the user/endpoint.

**Comment by autumnfound** [comment]
This has been merged in and completed.

**Comment by sdatspun2** [comment]
@autumnfound  Thanks for incorporating the Deprecation HTTP header. The name of the header is Deprecation as you can see from https://datatracker.ietf.org/doc/draft-dalal-deprecation-header/ . Example

Deprecation: Sun, 11 Nov 2018 23:59:59 GMT

Thanks.
@sdatspun2 @dret
